### ISSUE TITLE
Can't render grid function

### ISSUE THREAD

**Issue by raquel-aquino** [mattdesl/workshop-generative-art#12]
When trying to render the Drawing the Grid code, the browser page crashes when it gets to the const createGrid function. I've tried it with Firefox and Chrome and it didn't work out.

**The code:**
```
const canvasSketch = require('canvas-sketch');

const settings = {
  dimensions: [2048, 2048]
};

const sketch = () => {

  const createGrid = () => {
    const points = [];
    const count = 5;
    for (let x = 0; x < count; x++) {
      for (let y = 0; x < count; y++) {
        const u = x / count;
        const v = y / count;
        points.push ([u, v]);
      }
    }
    return points;
  };

  const points = createGrid();

  return ({ context, width, height }) => {
    context.fillStyle = 'white';
    context.fillRect(0, 0, width, height);

    points.forEach(([u, v]) => {
      const x = u * width;
      const y = v * height;

      context.beginPath();
      context.arc(x, y, 100, 0, Math.PI * 2, false);
      context.strokeStyle = 'black';
      context.lineWidth = 40;
      context.stroke();
    });
  };
};

canvasSketch(sketch, settings);
```

**The message I get on the Firefox console:**
Script terminated by timeout at:
createGrid

**Comment by mattdesl** [comment]
Hi Raquel, thanks for posting. I've never seen this error before, could you perhaps take a screenshot? Does this happen each time you open the page? What happens in Chrome? And could you let me know what your system specs are?

It might be the case that your computer is having a hard time running canvas projects—you could test [this Canvas benchmark](http://www.kevs3d.co.uk/dev/canvasmark/) to see how it runs, if that site is giving you rendering problems then it may be that your computer doesn't support Canvas2D very well. An alternative is to use an offline rendering approach for canvas-sketch, i.e. with [Node.js](https://github.com/mattdesl/canvas-sketch/blob/master/docs/exporting-artwork.md#node-export), but it's not as convenient and a little more complex.

**Comment by raquel-aquino** [comment]
Hi Matt, it turns out it was actually a typo on the second for (let y = 0; **x** < count; y++). I'm sorry for wasting your time!

**Comment by mattdesl** [comment]
No worries! Damn those infinite loops...
