### ISSUE TITLE
Font rendering issue

### ISSUE THREAD

**Issue by chrism** [mattdesl/workshop-generative-art#3]
Hi Matt,

Thanks again for the great course, I'm still trying to digest everything you covered!

Whilst going through the examples I've run into one issue.

I wanted to include a font in a sketch, so followed your Konami example and used async/await
https://github.com/mattdesl/workshop-generative-art/blob/master/src/2d/05-grid-konami.js

So my code looks something like like this:

```js
const sketch = async () => {
  const fontUrl = 'assets/fonts/IBMPlexMono-Regular.woff';
  const font = new window.FontFace(
    'IBMPlexMono-Regular',
    `url(${fontUrl})`
  );

  await font.load();
  console.log({ font });

  return ({ context, width, height }) => {
    context.fillStyle = 'white';
    context.fillRect(0, 0, width, height);

    const x = width / 2;
    const y = height / 2;

    context.fillStyle = 'black';
    context.font = `200px "IBMPlexMono-Regular"`;
    context.fillText('something', x, y);
  };
};
```

The log shows that the promise has fulfilled and the font should be available, but unfortunately it renders with the default serif font.

I cloned this repo to see if it was a problem with the way I copied your code, but I still see the same issue using your code too.

<img src="https://user-images.githubusercontent.com/35488/48720344-cc44c380-ec1f-11e8-9b21-4b785d4eda0c.png">

I wondered if this is a bug with the code, or a problem with my setup?

**Comment by mattdesl** [comment]
That's interesting! I'm not sure why it was working for me without adding it to the body, but I'll add this. :smile: Thanks for digging into it.
