### ISSUE TITLE
about camera-unproject 

### ISSUE THREAD

**Issue by jh531207323** [mattdesl/workshop-generative-art#5]
@mattdesl 
hi ,I have no way to contact you
so, just create a issue of you .
your camer-unproject of npm project is great.

but i can't use it. i don't know how to call it.

var mat4 = require('gl-mat4')
var unproject = require('camera-unproject')

what's mean of the parameter  projection,view,viewport,point  ?
can you provider a demo?

//projection * view matrix
var combinedProjView = mat4.multiply([], projection, view)
 
//now invert it
var invProjView = mat4.invert([], combinedProjView)
 
//viewport bounds
var viewport = [x, y, width, height]
 
//2D point in screen space
//z=0 means "near plane"
var point = [123, 52, 0]
 
//vec3 output
var output = []
 
unproject(output, point, viewport, invProjView)

**Comment by mattdesl** [comment]
Hey,

Unprojection in this context is the act of taking a 2D screen point (like XY pixel coordinate) and converting it into a 3D coordinate. It involves a bit of understanding of matrix math, projection matrices and so forth. There is some documentation in its [readme](https://github.com/Jam3/camera-unproject).

Cheers
