### ISSUE TITLE
Example with OBJ exporter

### ISSUE THREAD

**Issue by MatthewGreenberg** [mattdesl/workshop-generative-art#9]
Would be great, and would supplement your video on Blender.

**Comment by MatthewGreenberg** [comment]
eh i figured it out. just add in something like:

window.addEventListener('click', () => exportToObj())

  function exportToObj() {
    var exporter = new OBJExporter()
    var result = exporter.parse(scene)
    console.log(result)
  }

closing.

**Comment by mattdesl** [comment]
You might like to read some of the docs on exporting custom file types, and also check the below example which exports OBJ along with PNG on file save.

https://gist.github.com/mattdesl/7dd34f2bec4cdfa3d8c42295dcf1297f
